### ISSUE TITLE
Initial Energy Problem

### ISSUE THREAD

**Issue by YukiHaruna0824** [liminchen/OptCuts#12]
When I run a big object (no connected component , not high genus surface , closure surface) , the initial energy's value is to be nan sometimes . How do i solve this problem ?

**Comment by liminchen** [comment]
Thanks for letting me know!! You can send me the input file that triggers the nan initial energy and I can check what happens.

**Comment by YukiHaruna0824** [comment]
https://drive.google.com/open?id=1rwHUBUSeKtz0OPCkJZdNMxu5Oj82lrDv
48.obj is open surface，antoher objects are closure surface
use default batch.py to run.

**Comment by liminchen** [comment]
Hi Yuki,

Thanks for your interest in OptCuts! I've checked the 3 meshes you sent me and it turns out that they all contain triangles with 0 area (e.g. 3 vertices on a single line).

I've added a check in the code so that it will report the triangle and its vertex indices when encountering this situation. I think you could clean up the meshes by removing those 0-area triangles using e.g. mesh simplification tools and then retry.

Thanks!
Minchen
