### ISSUE TITLE
Some mesh problem

### ISSUE THREAD

**Issue by YukiHaruna0824** [liminchen/OptCuts#14]
I use OptCuts to my object, but some mesh split so slowly.
I tried to adjust distortion bound, but this mesh split so slowly too.
This is my mesh :
https://drive.google.com/open?id=1w-D9C4mCm05pzI_CoN2XjzIJUir5pqzp

I use batch.py to run OptCuts.

**Comment by liminchen** [comment]
Looks like there are merging and splitting that are oscillating under bijectivity mode. Probably because there are some numerical issue on the energy of the scaffolds. I will try to fix it soon.
Meanwhile I tried to run it without scaffolding which turns out fine, and I can even push Ed down to 4.01. To try it you can modify the 12th line of batch.py to
`runCommand = FracCutsPath + ' 10 ' + meshFolderPath + inputModelNameI + ' 0.999 1 0 4.02 0 0'`

**Comment by liminchen** [comment]
I also took a look at the mesh and I saw many skinny triangles. Those could also make the scaffolding energy numerically inaccurate. But anyway I will see whether there's a way to fix it.

**Comment by YukiHaruna0824** [comment]
Thank you!! I will try it.
